import CLI.interface
import CLI.run_interface
import Hotel_manage_sys.bookings_module
import Hotel_manage_sys.rooms_module
import Hotel_manage_sys.customers_module
import Testing.Test_booking_module
import Testing.Test_rooms_module
import Testing.Test_rooms_module
